local ENABLE_NOTIFY_HOOK = true
local PRINT_DEBUG = true

local STATIC_DICT = {
    ["Speed"] = "速度",
    ["Guard Aimlock"] = "守卫自瞄",
    ["LookingAt"] = "视线方向",
    ["Closest"] = "最近",
    ["Auto Shoot"] = "自动射击",
    ["Auto Shoot Mode"] = "自动射击模式",
    ["Auto Shoot (Silent Aim)"] = "自动射击(静默瞄准)",
    ["Bullets Per Fire"] = "每次射击子弹数",
    ["Bullet Size"] = "子弹大小",
    ["Hitbox"] = "碰撞箱",
    ["Utilities"] = "实用工具",
    ["Insta Arcade (works outside the game)"] = "自动玩街机(游戏外有效)",
    ["Teleport Target Mode"] = "传送目标模式",
    ["Quick Teleport"] = "快速传送",
    ["Attach"] = "吸附/跟随",
    ["HNS Mode"] = "捉迷藏模式",
    ["Enable ESP"] = "启用透视",
    ["Box Fill, Box Outline,..."] = "填充框, 边框...",
    ["Tracer Mode"] = "追踪线模式",
    ["Over Head"] = "头顶",
    ["ESP Distance"] = "透视距离",
    ["ESP Performance Mode"] = "性能模式",
    ["Show Only My Team"] = "仅显示己方队伍",
    ["Show Only Enemy Team"] = "仅显示敌方队伍",
    ["Trail"] = "轨迹/拖尾",
    ["Pentathlon"] = "五人六足",
    ["Auto Ddakji"] = "自动打画片",
    ["Auto Flying Stone"] = "自动飞石子",
    ["Auto Gonggi"] = "自动抓石子",
    ["Gonggi QTE Speed"] = "抓石子QTE速度",
    ["Randomize QTE Speed"] = "随机QTE速度",
    ["Auto Spinning Top"] = "自动打陀螺",
    ["Spinning Top Speed"] = "陀螺速度",
    ["Randomize Balance Speed"] = "随机平衡速度",
    ["Auto Jegi"] = "自动踢毽子",
    ["Weapons to auto equip"] = "武器类型",
    ["Search..."] = "搜索...",
    ["Show Doors (Green | Cir/Tri/Sqr)"] = "透视门 (绿 | 圆/三/方)",
    ["Key System"] = "卡密系统",
    ["Loader | AX-SCRIPTS"] = "by 晓月lol",
    ["Themes"] = "主题",
    ["Background color"] = "背景颜色",
    ["Main color"] = "主要颜色",
    ["Accent color"] = "强调色",
    ["Outline color"] = "轮廓颜色",
    ["Font color"] = "字体颜色",
    ["Font Face"] = "字体样式",
    ["Theme list"] = "主题列表",
    ["Configuration"] = "配置",
    ["Config name"] = "配置名称",
    ["Create config"] = "创建配置",
    ["Config list"] = "配置列表",
    ["Load config"] = "加载配置",
    ["Overwrite config"] = "覆盖配置",
    ["Delete config"] = "删除配置",
    ["Refresh list"] = "刷新列表",
    ["Set as autoload"] = "设为自动加载",
    ["Custom theme name"] = "自定义主题名称",
    ["Create theme"] = "创建主题",
    ["Custom themes"] = "自定义主题",
    ["Load theme"] = "加载主题",
    ["Overwrite theme"] = "覆盖主题",
    ["Delete theme"] = "删除主题",
    ["Set as default"] = "设为默认",
    ["Reset default"] = "重置默认",
    ["UI Settings"] = "界面设置",
    ["Open Keybind Menu"] = "打开按键绑定菜单",
    ["Lock Button (Mobile)"] = "锁定按钮(手机)",
    ["Notification Side"] = "通知位置",
    ["Top-Right"] = "右上角",
    ["DPI Scale"] = "DPI 缩放",
    ["Menu bind"] = "菜单绑定键",
    ["Unload"] = "卸载脚本",
    ["Authentication"] = "验证",
    ["Enter Key"] = "输入卡密",
    ["Insert your key here"] = "在此输入卡密",
    ["Get Key (Linkvertise)"] = "获取卡密(Linkvertise)",
    ["Get Key (Work Ink)"] = "获取卡密(Work Ink)",
    ["Check Key"] = "检查卡密",
    ["Join Discord"] = "加入Discord",
    ["Default"] = "默认",
    ["Midnight Orchid"] = "午夜兰花",
    ["Desert Storm"] = "沙漠风暴",
    ["Tropical Punch"] = "热带风情",
    ["Graphite"] = "石墨黑",
    ["Peacock Feather"] = "孔雀羽",
    ["Candy Cane"] = "糖果手杖",
    ["Dust Bowl"] = "尘暴",
    ["Inferno"] = "地狱火",
    ["Copper Canyon"] = "铜色峡谷",
    ["Vodka Lime"] = "伏特加莱姆",
    ["Stormy Night"] = "暴风雨之夜",
    ["Sunrise Glow"] = "日出光辉",
    ["Marshmallow"] = "棉花糖",
    ["Jade Forest"] = "翡翠森林",
    ["Steel Blue"] = "钢蓝",
    ["Peanut Butter"] = "花生酱",
    ["Ocean Pearl"] = "海洋珍珠",
    ["Berry Smoothie"] = "浆果冰沙",
    ["Mocha Mist"] = "摩卡迷雾",
    ["Celestial"] = "天体",
    ["Opal Glow"] = "蛋白石光辉",
    ["Electric Lime"] = "电光莱姆",
    ["Twilight"] = "暮光",
    ["Dusty Rose"] = "尘玫瑰",
    ["Mint Chocolate"] = "薄荷巧克力",
    ["Ocean Breeze"] = "海风",
    ["Crimson Tide"] = "深红潮汐",
    ["Lavender Mist"] = "薰衣草迷雾",
    ["Mystic Violet"] = "神秘紫",
    ["Goldenrod"] = "金麒麟",
    ["Canyon Clay"] = "峡谷粘土",
    ["Iceberg"] = "冰山",
    ["Peach Fuzz"] = "桃绒",
    ["Slate Grey"] = "板岩灰",
    ["Buttercup"] = "毛茛黄",
    ["Neon Jungle"] = "霓虹丛林",
    ["Midnight Blue"] = "午夜蓝",
    ["Rose Quartz"] = "粉晶",
    ["Sandstone"] = "砂岩",
    ["Lunar Eclipse"] = "月食",
    ["Flame Ember"] = "火焰余烬",
    ["Glacial"] = "冰河",
    ["Sunset Horizon"] = "日落地平线",
    ["Retro Wave"] = "复古波",
    ["Forest Mist"] = "森林迷雾",
    ["Deep Space"] = "深空",
    ["Candy Pop"] = "糖果流行",
    ["Vintage Paper"] = "复古纸",
    ["Oceanic Next"] = "海洋次世代",
    ["Material"] = "材质",
    ["Solar Flare"] = "太阳耀斑",
    ["Aurora"] = "极光",
    ["Emerald Dream"] = "翡翠梦境",
    ["Monokai"] = "Monokai主题",
    ["Gruvbox"] = "Gruvbox主题",
    ["Solarized"] = "Solarized主题",
    ["Catppuccin"] = "Catppuccin主题",
    ["One Dark"] = "One Dark主题",
    ["Cyberpunk"] = "赛博朋克",
    ["Tokyo Night"] = "东京之夜",
    ["Ubuntu"] = "Ubuntu主题",
    ["Quartz"] = "石英",
    ["Nord"] = "Nord主题",
    ["Dracula"] = "德古拉",
    ["Mspaint"] = "画图",
    ["BBot"] = "BBot",
    ["Fatality"] = "致命",
    ["Jester"] = "小丑",
    ["Mint"] = "薄荷",
    ["AX-SCRIPTS"] = "AX脚本-汉化",
    ["Ink Game | by AlexScriptX | Rewrite Beta (Freemium)"] = "by 晓月lol",
    ["Red Light, Green Light"] = "一二三木头人",
    ["God Mode"] = "无敌模式",
    ["Finish Red Light, Green Light"] = "传送至终点",
    ["Select Injured Player"] = "选择受伤玩家",
    ["Random"] = "随机",
    ["Help the Injured"] = "随机帮玩家到终点",
    ["Troll the Injured"] = "把玩家送回起点",
    ["Dalgona"] = "抠糖饼",
    ["Auto Dalgona"] = "自动抠糖饼",
    ["Auto Dalgona (all execs)"] = "自动抠糖饼(所有注入器可用)",
    ["Auto Dalgona (without hookfunction)"] = "自动抠糖饼(无hook函数)",
    ["Tug of War"] = "拔河",
    ["Rope Pull Mode"] = "拔河模式",
    ["Rage"] = "狂暴",
    ["Auto Pull Rope"] = "自动拔河",
    ["Glass Bridge"] = "玻璃桥",
    ["Reveal Safe & Fake Glass"] = "透视玻璃桥",
    ["Finish Glass Bridge"] = "传送至终点",
    ["Mingle"] = "旋转木马",
    ["QTE Mode"] = "QTE模式",
    ["Legit"] = "正常",
    ["Auto Choke"] = "自动锁喉",
    ["Jump Rope"] = "跳绳",
    ["Finish Jump Rope"] = "传送至终点",
    ["Disable Rope (Anti Death)"] = "删除绳子",
    ["Auto Balance"] = "自动平衡",
    ["Use this one only if you died after the cutscene:"] = "仅在过场动画后使用：",
    ["Anti die after cutscene"] = "防死亡",
    ["Safe Zone (Last Dinner)"] = "传送至安全点(最后的晚餐)",
    ["Last Dinner"] = "最后的晚餐",
    ["Squid Game"] = "鱿鱼游戏",
    ["Float Above Fight Arena"] = "悬浮到场地上",
    ["Lights Out"] = "熄灯",
    ["Safe Zone"] = "传送至安全点",
    ["Hide N' Seek"] = "捉迷藏",
    ["Show Exit Doors (Yellow)"] = "透视逃生门",
    ["Show Doors (Cir/Tri/Sqr)"] = "透视门",
    ["Show Players (Red/Blue)"] = "透视玩家(红/蓝)",
    ["Exclude Own Team"] = "排除自己的队伍",
    ["Exclude Opposing Team"] = "排除敌方队伍",
    ["Show Dropped Keys (Purple)"] = "透视掉落的钥匙",
    ["Show Staircases (Brown)"] = "透视楼梯",
    ["Show Spikes (Black)"] = "透视尖刺",
    ["Auto Collect Dropped Keys"] = "自动收集掉落的钥匙",
    ["Auto Dodge"] = "自动躲避",
    ["Auto Knife"] = "自动攻击",
    ["Infinite Stamina"] = "无限体力",
    ["Attach Hider"] = "贴在躲藏者后面",
    ["Movement Type"] = "攻击类型",
    ["Offset X"] = "偏向X",
    ["Teleport"] = "传送",
    ["Offset Z"] = "偏向Z",
    ["Teleport to Hider"] = "传送至躲藏者",
    ["Rebel"] = "反叛",
    ["Bring Guards"] = "聚集守卫",
    ["Guards Hitbox + ESP"] = "扩大守卫碰撞箱+透视",
    ["Guards Hitbox Size"] = "碰撞箱大小",
    ["Sky Squid Game"] = "天空鱿鱼游戏",
    ["Auto QTEs"] = "自动按QTE",
    ["Auto Climb"] = "自动攀爬",
    ["Instant Climb"] = "即时攀爬",
    ["Anti Fall"] = "防坠落",
    ["Auto-Win"] = "自动赢",
    ["Games"] = "游戏",
    ["Modded Gun"] = "改装枪械",
    ["Autowin"] = "自动赢",
    ["Aimlock Mode"] = "自瞄模式",
    ["Enable Aimlock"] = "启用自瞄",
    ["Teleport to Random Player"] = "传送至随机的玩家",
    ["Show Players"] = "透视玩家",
    ["Kill Aura"] = "杀戮光环",
    ["Auto Equip Tool"] = "自动装备武器",
    ["Auto Attack"] = "自动攻击",
    ["Auto Face Target"] = "自动面对目标",
    ["Attach Target"] = "自动贴紧玩家",
    ["Select Target Player"] = "选择玩家",
    ["Follow Movement Type"] = "方式",
    ["Miscs"] = "杂项",
    ["Select Emote"] = "选择表情",
    ["Play/Pause Emote"] = "做/停止表情",
    ["Select Vote"] = "选择投票选项",
    ["Extras"] = "附加内容",
    ["Auto Vote"] = "自动投票",
    ["Auto Skip Dialogue"] = "自动跳过对话",
    ["Auto Next Game"] = "自动下一个游戏",
    ["Disable Effects"] = "禁用效果",
    ["Fullbright"] = "高亮",
    ["Collect Dropped Bandages"] = "收集掉落的绷带",
    ["Instant Interact"] = "即时互动",
    ["Interact Reach"] = "互动覆盖率",
    ["Lobby"] = "大厅",
    ["Auto New Round"] = "自动新一轮",
    ["Auto Return Lobby"] = "自动返回大厅",
    ["Player (NOT FE)"] = "玩家(非fe)",
    ["Noclip"] = "穿墙",
    ["Fly"] = "飞行",
    ["Emotes"] = "表情",
    ["Fly Speed"] = "飞行速度",
    ["Hide Nametag"] = "隐藏称号",
    ["Select Title"] = "选择称号",
    ["Equip Title"] = "装备称号",
    ["Select Power"] = "选择职业",
    ["Equip Power"] = "解锁职业",
    ["Disable Dash Cooldown"] = "冲刺无冷却",
    ["Disable Double Jump Cooldown"] = "双跳无冷却",
    ["Boosts"] = "属性等级调整",
    ["Damage Boost (NOT FE)"] = "力量等级",
    ["Faster Sprint (5 TO UNLOCK DASH)"] = "调整冲刺",
    ["Won Boost (NOT FE)"] = "胜利加成等级",
    ["Jump Boost"] = "跳跃高度",
    ["Always Can Revive"] = "复活无限制",
    ["Spectate"] = "启用观战模式",
    ["Disable Injury"] = "移除受伤效果",
    ["Disable Stun"] = "无眩晕",
    ["Disable Ragdoll"] = "防布娃娃",
    ["Gamepasses (NOT FE)"] = "游戏通行证",
    ["Enable VIP"] = "解锁vip",
    ["Glass Manufacturer Vision"] = "解锁玻璃制造商",
    ["2x Vote Count"] = "解锁双倍投票",
    ["Custom Player Tag (NOT FE)"] = "自定义玩家标签",
    ["Custom Player Tag"] = "自定义玩家标签",
    ["Set a custom tag"] = "设置自定义标签",
    ["Security"] = "安全",
    ["Anti AFK"] = "防AFK",
    ["Staff Detector"] = "检测管理员",
    ["Combat"] = "战斗类",
    ["Players"] = "玩家",
    ["Player Info"] = "玩家信息",
    ["Select a player to view info"] = "选择一个玩家获取他的信息",
    ["Select Player"] = "选择玩家",
    ["Biggest Threat"] = "获取信息",
    ["Settings"] = "设置",
    ["Toggle"] = "开关",
    ["Lock"] = "锁定",
    ["Unlock"] = "取消锁定",
    ["ESP Elements"] = "ESP方式",
    ["Box Type"] = "碰撞箱类型",
    ["Pickup Keys"] = "自动捡钥匙",
    ["Fast Sprint"] = "解锁快速冲刺",
    ["Ink Game | by AlexScriptX | Free"] = "by 晓月lol",
    ["Peabert"] = "狗哥",
    ["Select Peabert"] = "选择地图上的狗哥",
    ["TP"] = "传送",
    ["Get All"] = "获取全部",
    ["Select Players"] = "选择玩家",
    ["Face Target"] = "面对目标",
    ["Pickup Bandages"] = "自动捡绷带",
    ["Emote Pages"] = "解锁表情菜单",
    ["Perfect"] = "完美",
    ["Normal"] = "正常",
    ["Troll"] = "必输",
    ["Disable Spikes"] = "删除尖刺",
    ["Auto Equip Weapons"] = "自动装备武器",
    ["Kill Aura Range"] = "杀戮光环范围",
    ["Get Lighter"] = "获取打火机",
    ["Anti Fling"] = "防甩飞",
    ["Auto Dalgona V2"] = "自动扣糖饼v2",
    ["Auto Dalgona V3"] = "自动扣糖饼v3",
    ["Ultra Rage"] = "超级狂暴模式",
    ["Select Kill Target"] = "选择类型",
    ["Kill a Player"] = "自动杀死玩家",
    ["Kill Aura Target"] = "杀戮光环类型",
    ["Offset X (Right/Left)"] = "偏向x轴距离",
    ["Offset Y (Up/Down)"] = "偏向y轴距离",
    ["Offset Z (Front/Back)"] = "偏向z轴距离",
    ["Auto Unlock Rewards"] = "自动解锁奖励",
    ["Anti Void"] = "防虚空",
    ["Kill Aura Whitelist"] = "玩家名单",
    ["Show Visualizer"] = "显示可视化工具",
    ["Pull Rope"] = "自动拔河",
    ["Spikes Kill"] = "把躲藏者传送至尖刺",
    ["Hitbox Size"] = "守卫碰撞箱大小",
    ["Hitbox Transparency"] = "碰撞箱透明度",
    ["Guns"] = "枪械",
    ["Modded Guns"] = "枪械强化",
    ["Zone Kill"] = "把玩家传送到场地外杀死",
    ["Anti Break Glass"] = "防坠落",
    ["Action"] = "类型",
    ["Auto Help/Troll"] = "自动把玩家送至终点/起点",
    ["Help/Troll Injured"] = "把玩家送至起点/终点",
    ["If you plan to use the Lighter along with Anti Crack, make sure to:"] = "首先",
    ["1. Crack the cookie once first"] = "开启糖饼不破",
    ["2. Then activate Anti Crack"] = "然后点击获取打火机",
    ["3. Finally, enable the Lighter"] = "就可以了",
    ["Anti Crack"] = "糖饼不破",
    ["Disable Game"] = "删除绳子",
    ["Simulate Balance"] = "保持平衡",
    ["Auto Jump"] = "自动跳跃",
    ["Fix Broken Tracks"] = "修复损坏的平台",
    ["Unlimited Chances"] = "无限平衡次数",
    ["Attach Target/Hider"] = "贴到躲藏者后面",
    ["Bypass Rope"] = "绕过绳子限制",
    ["Press Speed"] = "点击速度",
    ["Randomize Press Speed"] = "随机点击速度",
    ["Auto QTE"] = "自动按QTE",
    ["Press Button"] = "显示点击按钮",
    ["Get Pole"] = "自动拿钢管",
    ["Void Kill"] = "把玩家传送至虚空",
    ["Enable/Disable Aimlock"] = "启用自瞄",
    ["Target Mode"] = "模式",
    ["Specific Player"] = "选择玩家",
    ["Teleport to Target"] = "传送至选定的玩家",
    ["Quick Teleport to Specific Player"] = "快速传送至指定玩家",
    ["Prediction"] = "启用预判",
    ["Show Range"] = "显示范围",
    ["Tracer Position"] = "追踪线位置",
    ["Select Players (Empty = All)"] = "选择玩家",
    ["Exclude Enemy Team"] = "排除敌方队伍",
    ["Wall Check"] = "墙壁检测",
    ["Faster Sprint (5+ TO UNLOCK DASH)"] = "速度调整",
    ["Hide Other Nametags"] = "隐藏其他标签",
    ["Parkour Artist Mods"] = "强化跑酷大师",
    ["Anti Ragdoll"] = "移除受伤效果",
    ["Emote Speed"] = "速度",
    ["Low GFX"] = "提高帧数",
    ["FOV Changer"] = "视野调整",
    ["Peabert ESP"] = "狗哥透视",
    ["Teleport to Peabert"] = "传送至狗哥",
    ["Select Guns"] = "选择枪械",
    ["Bullets"] = "最大子弹数",
    ["Range"] = "范围",
    ["Fire Rate CD"] = "射速冷却",
    ["Run Speed"] = "执行速度",
    ["Spread"] = "散布范围",
    ["Scope FOV"] = "瞄准镜视野",
    ["Walk Speed"] = "行走速度",
    ["If you plan to use the Lighter along with Anti Crack, make sure to:\n1. Crack the cookie once first\n2. Then activate Anti Crack\n3. Finally, enable the Lighter "] = "先点击获取打火机，然后开启糖饼不破",
    ["Halloween"] = "万圣节活动",
    ["Guards"] = "守卫",
    ["Hitbox Expander"] = "扩大玩家碰撞箱",
    ["Rebel Hitbox"] = "扩大反叛玩家碰撞箱",
    ["Guard Shape"] = "守卫类型",
    ["Circle"] = "圆形守卫",
    ["Spawn as Guard"] = "自动当选的守卫(前提是得有钱)",
    ["Insta Claw Machine"] = "自动抓娃娃",
    ["Insta Arcade"] = "自动玩街机",
    ["Ink Game | by AlexScriptX | Premium"] = "AX付费版 by 晓月lol",
    ["Triangle"] = "三角形守卫",
    ["Square"] = "正方形守卫",
    ["Doors ESP"] = "透视门",
    ["Event"] = "活动",
    ["Teleport to Door"] = "传送至门",
    ["Candy ESP"] = "透视糖果",
    ["Select Candy"] = "选择糖果",
    ["Teleport to Candy"] = "传送至糖果",
    ["Box, Name, Health, Dis... "] = "盒子，名字，血量....",
    ["Health"] = "血量",
    ["Distance"] = "距离",
    ["Name"] = "名字",
    ["Box"] = "盒子",
    ["Tracer"] = "目标",
    ["Name Type"] = "名字类型",
    ["Username"] = "用户名",
    ["Manual"] = "手动",
    ["Get Rock"] = "获得石头",
    ["Auto Shoot Guards"] = "自动攻击守卫",
    ["Auto Stop"] = "自动暂停(红灯自动停)",
    ["Search"] = "搜索",
    ["Select Door"] = "选择门",
    ["Aimlock"] = "自瞄",
    ["Private Server+"] = "解锁高级私人服务器",
    ["Permanent Guard"] = "解锁守卫",
    ["Auto Cycle Colors"] = "自动切换颜色",
    ["Auto Cvele Fonts"] = "自动切换字体",
    ["Finish RLGL"] = "传送至终点",
    ["Whitelist"] = "玩家名单",
    ["Auto Attack Range"] = "范围",
    ["Ink Game | by AlexScriptX"] = "by 晓月lol",
    ["Select Exit Door"] = "选择逃生门",
    ["Teleport to Seeker"] = "传送至杀手",
    ["Custom Titles"] = "自定义称号",
    ["Auto Flying Stone (Remote)"] = "自动飞石子",
    ["Auto Gonggi (Remote)"] = "自动抓石子",
    ["Auto Spinning Top (Remote)"] = "自动转陀螺",
    ["Auto Jegi (Remote)"] = "自动踢毽子",
    ["Gonggi Auto QTE"] = "自动qte速度",
    ["Spinning Top Auto Balance"] = "自动平衡速度",
    ["Auto Ddakji (Remote)"] = "自动打画片",
    ["Faster Sprint (6+ TO UNLOCK DASH)"] = "速度等级",
    ["Barriers"] = "防坠落v2",
    ["Search:"] = "搜索",
    ["Stop Playing"] = "结束游戏",
    ["Keep Playing"] = "继续游戏",
    ["From Mouse"] = "鼠标",
    ["From Bottom"] = "下方",
    ["Fork, Bottle, Pole, Kn..."] = "选择武器",
    ["Form top"] = "顶端",
    ["ESP Mode"] = "透视模式",
    ["Lowest Health"] = "最低血量",
    ["Low Performance"] = "低性能",
    ["Teleport to Exit Door"] = "传送至随机逃生门",
    ["Auto Escape"] = "自动逃生",
    ["Tip:\nUse Rinku.pro for the fastest key"] = "不会解别解",
    ["QUICKSILVER"] = "快银",
    ["PARKOUR ARTIST"] = "跑酷大师",
    ["PHANTOM STEP"] = "幽灵步",
    ["LIGHTNING GOD"] = "闪电神",
    ["Get Key (Work.Ink)"] = "复制解卡链接(Work.ink)",
    ["Get Key (Rinku.pro)"] = "复制解卡链接(Rinku)",
    ["Luis Auto Goon"] = "撅管",
    ["No Recoil"] = "无后坐力",
    ["Skeleton"] = "骨骼",
    ["Health Bar"] = "血条",
    ["Health Number"] = "血量数值",
    ["Box Outline"] = "方框轮廓",
    ["Tool"] = "工具",
    ["ESP"] = "透视",
    ["Target"] = "朝向",
    ["Auto Collect Ornaments"] = "自动收集饰品",
    ["ESP Ornaments"] = "饰品透视",
    ["Teleport to Ornament"] = "传送到选择的饰品",
    ["Select an ornament"] = "选择一个饰品",
    ["Christmas"] = "圣诞节活动",
    ["Box Fill"] = "方框填充",
    ["Facing"] = "朝向",
    ["Custom Title Color"] = "自定义标题颜色",
    ["Faster Sprint (DONT USE DASH)"] = "速度调整",
    ["Custom Title Font"] = "自定义标题字体",
    ["Auto Cycle Fonts"] = "自动切换字体",
    ["Auto-load"] = "自动注入脚本",
    ["From Top"] = "顶部",
    ["Main"] = "主功能",
    ["Targeting Type"] = "目标选择方式",
    ["Nearest Player"] = "最近的玩家",
    ["Aim Part"] = "瞄准部位",
    ["Head"] = "头部",
    ["Target Specific Player"] = "指定目标玩家",
    ["Prioritize Players"] = "优先玩家",
    ["Ignore Players"] = "忽略玩家",
    ["Silent Aim"] = "子弹追踪",
    ["Target Certain Player"] = "锁定特定玩家",
    ["Ignore Shielded"] = "忽略护盾",
    ["Ignore Lobby"] = "忽略大厅",
    ["Enable FOV"] = "启用视野范围",
    ["Show FOV"] = "显示视野范围",
    ["FOV Size"] = "视野范围大小",
    ["Rainbow FOV"] = "彩虹视野圈",
    ["RGB Mode"] = "RGB模式",
    ["Enable Crosshair"] = "启用准星",
    ["Enable Blur"] = "启用模糊效果",
    ["Reset autoload"] = "重置自动加载",
    ["Current autoload config: none"] = "当前自动加载配置：无",
    ["Nearest Mouse"] = "距离鼠标最近",
    ["Torso"] = "身体",
    ["Feet"] = "脚部",
    ["FOV Color"] = "视野圈颜色",
    ["Studs"] = "单位",
    ["Preferences"] = "偏好设置",
    ["Flick | by AlexScriptX & moon"] = "当前服务器:闪光 | by 晓月lol",
    ["UpperTorso"] = "上躯干",
    ["HumanoidRootPart"] = "人形根部",
    ["LowerTorso"] = "下躯干",
    ["AutoFarm"] = "自动功能",
    ["Cashier"] = "自动收银",
    ["Cook"] = "自动烹饪",
    ["Boxer"] = "自动打包",
    ["Delivery"] = "自动送货",
    ["Supplier"] = "自动进披萨",
    ["Enable All Jobs"] = "解锁所有工作",
    ["Disable All Jobs"] = "禁用所有工作",
    ["Config"] = "配置",
    ["Refill At"] = "补充数量",
    ["Refill End"] = "补充结束时间",
    ["Deliver At"] = "送达时间",
    ["Prevent Sitting"] = "防坐下",
    ["Auto Collect Money & Stickers"] = "自动收集金钱和贴纸",
    ["Work at a Pizza Place | by AlexScriptX"] = "当前服务器:在披萨店工作 | by 晓月lol",
    ["Change Dash Cooldown"] = "调整冲刺冷却",
    ["Dash Cooldown"] = "冲刺冷却",
    ["Faster Sprint"] = "速度等级",
    ["This also works for the Ping Pong minigame for guards"] = "这个在守卫的乒乓球游戏里也一样能用",
    ["Anti Stun"] = "防眩晕",
    ["Ignore Enemy Team"] = "忽略敌方队伍",
    ["Space/Q"] = "空格/Q",
    ["Space/LeftControl"] = "空格/左Ctrl",
    ["Anti Injury"] = "移除受伤",
    ["Custom Shoot Speed (ms): 100"] = "自定义射速 (ms): 100",
    ["E/Q"] = "E/Q",
    ["Space/LeftShift"] = "空格/左Shift",
    ["Direct"] = "直接",
    ["MoveDirection"] = "移动方向",
    ["Input Mode"] = "输入模式",
    ["KeyPress"] = "按键触发",
    ["VirtualInputManager"] = "虚拟输入",
    ["ControlModule"] = "控制模块",
    ["Fly Up/Down Keys"] = "飞行上升/下降键",
    ["Leave on Low Life"] = "残血自动退出",
    ["The following remote features require a manual Re-Hook if the automatic one fails to get the necessary minigame information for the remotes to work"] = "如果自动获取游戏信息失败，以下功能需要重新re hook才能用",
    ["Show Dead Players"] = "显示死亡玩家",
    ["ESP Font"] = "透视字体",
    ["Break Fake Glass"] = "打碎所有假玻璃",
    ["Breaks all fake glass panels at once"] = "一次性击碎所有假玻璃板",
    ["Fly Movement Mode"] = "飞行模式",
    ["Monospace"] = "等宽字体",
    ["System"] = "系统字体",
    ["Team Colors"] = "队伍颜色",
    ["Plex"] = "Plex字体",
    ["Select Target"] = "选择目标",
    ["Dynamic Box Sizing"] = "启用动态方框",
    ["UI"] = "ui字体",
    ["Ignore My Team"] = "忽略友方队伍",
    ["Show Local Player"] = "显示本地玩家",
    ["Target Part"] = "目标部位",
    ["Click TP"] = "点击传送",
    ["Exclude Players"] = "忽略玩家",
    ["Guard ESP"] = "守卫透视",
    ["TP On Low Health"] = "残血自动传送",
    ["Guard Hitbox"] = "守卫攻击范围"
}
local DYNAMIC_DICT = {
    { "^Health:%s*(%d+)", "血量：%1" },
    { "^Distance:%s*(%d+)", "距离：%1" },
    { "^Distance%s*(%d+)m", "距离：%1米" },
    { "^Bullets:%s*(%d+/%d+)", "子弹：%1" },
    { "^Speed%sx(%d+)", "速度 x%1" },
    { "^Range:%s(%d+)", "范围：%1" },
    { "^Walk Speed:%s*(%d+)", "行走速度：%1" },
    { "^Run Speed:%s*(%d+)", "执行速度：%1" },
    { "^Backflip Cooldown:%s*(%d+)", "后空翻冷却时间：%1秒" },
    { "^Backflip Height:%s*(%d+)", "后空翻高度：%1" },
    { "^Slide Cooldown:%s*(%d+)", "滑铲冷却：%1" },
    { "^Slide Initial Speed:%s*(%d+)", "滑铲初始速度：%1" },
    { "^Interact Reach", "交互距离" },
    { "^FOV Value", "视野大小" },
    { "studs", "米" },
    { "Custom Shoot Speed (ms)", "射速" },
    {
        "Player:%s*(.-)\n.-Wins:%s*(%d+)\n.-Level:%s*(%d+)\n.-Power:%s*(.-)\n.-Won:%s*([%d,]+)\n.-Roll%(%ss%):%s(%d+)\n.-Robux Donated:%s*(%d+)\n.-VIP:%s*(Yes|No)\n.-Lighter:%s*(Yes|No)\n.-2X Vote:%s*(Yes|No)\n.-Glass Manufacturer:%s*(Yes|No)\n.-Upgrades:.-Faster Speed:%s*(%d+).-\nStrength Boost:%s*(%d+).-\nWon Boost:%s*(%d+).-\nUnlocked Powers:%s*(.+)",
        "玩家：%1\n胜利次数：%2\n等级：%3\n能力：%4\n赢得金额：%5\n抽取次数：%6\n捐赠Robux：%7\nVIP：%8\n打火机：%9\n2倍投票：%10\n玻璃制造商：%11\n\n升级：\n移动速度提升：%12\n力量提升：%13\n胜利加成：%14\n\n已解锁能力：\n%15"
    },
    { "Medic", "医疗兵" },
    { "Trickster", "诡术师" },
    { "Blackflash", "黑闪" },
    { "Weapon Smuggler", "武器走私者" },
    { "Phantom Step", "幽灵步" },
    { "Parkour Artist", "跑酷大师" },
    { "Player 120", "120级玩家" },
    { "Hercules", "大力神" },
    { "Bulldozer", "推土机" },
    { "Super Strength", "超级力量" },
    { "Player 100", "100级玩家" },
    { "Coin Flip", "抛硬币" },
    { "Ultra Instinct", "自在极意" },
    { "Headless Horseman", "无头骑士" },
    { "Necromancer", "死灵法师" },
    { "The Doctor", "医生" },
    { "Snowball Launcher", "雪球发射器" },
    { "Custom Shoot Speed (ms):", "射速" }
}
local processed = setmetatable({}, { __mode = "k" })
local function translate(text)
    if type(text) ~= "string" then return nil end
    local s = STATIC_DICT[text]
    if s then return s end
    for i = 1, #DYNAMIC_DICT do
        local rule = DYNAMIC_DICT[i]
        local new, count = text:gsub(rule[1], rule[2])
        if count > 0 then
            return new
        end
    end
    return nil
end

local function applyGradient(inst)
    if inst:FindFirstChild("TranslateGradient") then return end
    if inst:FindFirstChild("SpecialGradient") then
        inst.SpecialGradient:Destroy()
    end
    local gradient = Instance.new("UIGradient")
    gradient.Name = "TranslateGradient"
    gradient.Rotation = 90
    gradient.Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0.00, Color3.fromRGB(255, 255, 255)),
        ColorSequenceKeypoint.new(1.00, Color3.fromRGB(180, 180, 180))
    })
    gradient.Parent = inst
    inst.TextColor3 = Color3.fromRGB(255, 255, 255)
end

local function applySpecialGradient(inst)
    if inst:FindFirstChild("SpecialGradient") then return end
    if inst:FindFirstChild("TranslateGradient") then
        inst.TranslateGradient:Destroy()
    end

    local gradient = Instance.new("UIGradient")
    gradient.Name = "SpecialGradient"
    gradient.Rotation = 0
    gradient.Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0.00, Color3.fromRGB(255, 0, 0)),
        ColorSequenceKeypoint.new(0.20, Color3.fromRGB(255, 165, 0)),
        ColorSequenceKeypoint.new(0.40, Color3.fromRGB(255, 255, 0)),
        ColorSequenceKeypoint.new(0.60, Color3.fromRGB(0, 255, 0)),
        ColorSequenceKeypoint.new(0.80, Color3.fromRGB(0, 255, 255)),
        ColorSequenceKeypoint.new(1.00, Color3.fromRGB(170, 0, 255))
    })
    gradient.Parent = inst
    inst.TextColor3 = Color3.fromRGB(255, 255, 255)
end

local function handleTextInstance(inst)
    if processed[inst] then return end
    processed[inst] = true
    local txt = inst.Text
    if type(txt) ~= "string" then return end
    local new = translate(txt)
    if new then
        inst.Text = new
        if new == "AX脚本-汉化" then
            applySpecialGradient(inst)
        else
            applyGradient(inst)
        end
    end
    inst:GetPropertyChangedSignal("Text"):Connect(function()
        local t = inst.Text
        if type(t) ~= "string" then return end

        local r = translate(t)
        if r then
            inst.Text = r
            if r == "AX脚本-汉化" then
                applySpecialGradient(inst)
            else
                applyGradient(inst)
            end
        end
    end)
end

local function isTextInstance(inst)
    return inst:IsA("TextLabel") or
           inst:IsA("TextButton") or
           inst:IsA("TextBox")
end
for _, v in ipairs(game:GetDescendants()) do
    if isTextInstance(v) then
        handleTextInstance(v)
    end
end

game.DescendantAdded:Connect(function(v)
    if isTextInstance(v) then
        handleTextInstance(v)
    end
end)

if ENABLE_NOTIFY_HOOK and getgc then
    task.spawn(function()
        for _, v in pairs(getgc(true)) do
            if type(v) == "table" and type(rawget(v, "Notify")) == "function" then
                local old = v.Notify
                v.Notify = function(self, text, ...)
                    if type(text) == "string" then
                        text = translate(text) or text
                    end
                    return old(self, text, ...)
                end
            end
        end
    end)
end

loadstring(game:HttpGet("https://officialaxscripts.vercel.app/scripts/AX-Loader.lua"))()